#!/usr/bin/env bash
#
# Regenerate Discovery0Locked.h from the golden fixture
# test/fixtures/opal/discovery0-locked.bin (the shared fake-Opal spec's
# byte-exact Level 0 Discovery response — see test/fixtures/opal/README.md).
#
#   gen-discovery-header.sh           rewrite Discovery0Locked.h
#   gen-discovery-header.sh --check   fail if the checked-in header is stale
#
# The header is checked in so the EDK2 build needs no generation step;
# build.sh runs --check as a drift guard.

set -euo pipefail

HERE="$(dirname "$(readlink -f "$0")")"
FIXTURE="$HERE/../fixtures/opal/discovery0-locked.bin"
OUT="$HERE/Discovery0Locked.h"

generate() {
	python3 - "$FIXTURE" <<'EOF'
import sys

data = open(sys.argv[1], "rb").read()
print(f"""\
/* Generated by gen-discovery-header.sh from
   test/fixtures/opal/discovery0-locked.bin ({len(data)} bytes) — the golden
   Level 0 Discovery response of the canonical locked device
   (test/fixtures/opal/README.md). DO NOT EDIT; regenerate instead. */
#ifndef DISCOVERY0_LOCKED_H_
#define DISCOVERY0_LOCKED_H_

STATIC CONST UINT8 mDiscovery0Locked[{len(data)}] = {{""")
for i in range(0, len(data), 12):
    chunk = ", ".join(f"0x{b:02X}" for b in data[i:i + 12])
    print(f"  {chunk},")
print("};\n\n#endif /* DISCOVERY0_LOCKED_H_ */")
EOF
}

if [ "${1:-}" = "--check" ]; then
	if ! generate | diff -u "$OUT" - >&2; then
		echo "error: $OUT is stale; run $0 to regenerate" >&2
		exit 1
	fi
else
	generate > "$OUT"
	echo "wrote $OUT"
fi
